/**
 * @file autonomous_t26.c
 *
 * @brief This source file was generated by cantools version 41.3.0 Fri Apr 10 18:19:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "dbc/autonomous_t26.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int autonomous_t26_acu_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_acu_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ign, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->asms, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->emergency, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->as_state, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 6u, 0xc0u);
    dst_p[1] |= pack_right_shift_u8(src_p->mission_select, 2u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->acu_state, 1u, 0x1eu);
    dst_p[1] |= pack_left_shift_u8(src_p->assi_state, 5u, 0xe0u);
    dst_p[2] |= pack_right_shift_u8(src_p->assi_state, 3u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->acu_cpu_temp, 1u, 0xfeu);
    dst_p[3] |= pack_right_shift_u8(src_p->acu_cpu_temp, 7u, 0x01u);

    return (8);
}

int autonomous_t26_acu_unpack(
    struct autonomous_t26_acu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ign = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->asms = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->emergency = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->as_state = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->mission_select |= unpack_left_shift_u8(src_p[1], 2u, 0x01u);
    dst_p->acu_state = unpack_right_shift_u8(src_p[1], 1u, 0x1eu);
    dst_p->assi_state = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->assi_state |= unpack_left_shift_u8(src_p[2], 3u, 0x01u);
    dst_p->acu_cpu_temp = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);
    dst_p->acu_cpu_temp |= unpack_left_shift_u8(src_p[3], 7u, 0x01u);

    return (0);
}

int autonomous_t26_acu_init(struct autonomous_t26_acu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_acu_t));

    return 0;
}

uint8_t autonomous_t26_acu_ign_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_ign_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_ign_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_acu_ign_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t autonomous_t26_acu_asms_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_asms_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_asms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_acu_asms_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t autonomous_t26_acu_emergency_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_emergency_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_emergency_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_acu_emergency_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t autonomous_t26_acu_as_state_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_as_state_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_as_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool autonomous_t26_acu_as_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_acu_mission_select_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_mission_select_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_mission_select_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool autonomous_t26_acu_mission_select_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_acu_acu_state_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_acu_state_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_acu_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool autonomous_t26_acu_acu_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_acu_assi_state_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_assi_state_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_assi_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool autonomous_t26_acu_assi_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_acu_acu_cpu_temp_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_acu_acu_cpu_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_acu_acu_cpu_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_acu_acu_cpu_temp_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int autonomous_t26_dir_actuator_feedback_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_dir_actuator_feedback_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->position, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->position, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->current, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->current, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->error_codes, 0u, 0xffu);

    return (8);
}

int autonomous_t26_dir_actuator_feedback_unpack(
    struct autonomous_t26_dir_actuator_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->position = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->position |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->speed = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->current = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->current |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->temperature = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->error_codes = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int autonomous_t26_dir_actuator_feedback_init(struct autonomous_t26_dir_actuator_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_dir_actuator_feedback_t));

    return 0;
}

uint16_t autonomous_t26_dir_actuator_feedback_position_encode(double value)
{
    return (uint16_t)(value / 10.0);
}

double autonomous_t26_dir_actuator_feedback_position_decode(uint16_t value)
{
    return ((double)value * 10.0);
}

bool autonomous_t26_dir_actuator_feedback_position_is_in_range(uint16_t value)
{
    return (value <= 3200u);
}

bool autonomous_t26_dir_actuator_feedback_position_is_in_phys_range(double value)
{
    return ((value >= -32000.0) && (value <= 32000.0));
}

uint16_t autonomous_t26_dir_actuator_feedback_speed_encode(double value)
{
    return (uint16_t)(value / 210.0);
}

double autonomous_t26_dir_actuator_feedback_speed_decode(uint16_t value)
{
    return ((double)value * 210.0);
}

bool autonomous_t26_dir_actuator_feedback_speed_is_in_range(uint16_t value)
{
    return (value <= 152u);
}

bool autonomous_t26_dir_actuator_feedback_speed_is_in_phys_range(double value)
{
    return ((value >= -32000.0) && (value <= 32000.0));
}

uint16_t autonomous_t26_dir_actuator_feedback_current_encode(double value)
{
    return (uint16_t)(value / 100.0);
}

double autonomous_t26_dir_actuator_feedback_current_decode(uint16_t value)
{
    return ((double)value * 100.0);
}

bool autonomous_t26_dir_actuator_feedback_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_dir_actuator_feedback_current_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_dir_actuator_feedback_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_dir_actuator_feedback_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_dir_actuator_feedback_temperature_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool autonomous_t26_dir_actuator_feedback_temperature_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 127.0));
}

uint8_t autonomous_t26_dir_actuator_feedback_error_codes_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_dir_actuator_feedback_error_codes_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_dir_actuator_feedback_error_codes_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool autonomous_t26_dir_actuator_feedback_error_codes_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

int autonomous_t26_dir_act_possition_loop_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_dir_act_possition_loop_t *src_p,
    size_t size)
{
    uint32_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint32_t)src_p->position;
    dst_p[0] |= pack_right_shift_u32(position, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(position, 0u, 0xffu);

    return (8);
}

int autonomous_t26_dir_act_possition_loop_unpack(
    struct autonomous_t26_dir_act_possition_loop_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->position = (int32_t)position;

    return (0);
}

int autonomous_t26_dir_act_possition_loop_init(struct autonomous_t26_dir_act_possition_loop_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_dir_act_possition_loop_t));

    return 0;
}

int32_t autonomous_t26_dir_act_possition_loop_position_encode(double value)
{
    return (int32_t)(value / 1000.0);
}

double autonomous_t26_dir_act_possition_loop_position_decode(int32_t value)
{
    return ((double)value * 1000.0);
}

bool autonomous_t26_dir_act_possition_loop_position_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_dir_act_possition_loop_position_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int autonomous_t26_aqt1_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt1_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->brk_press, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brk_press, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->res, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->bots, 1u, 0x02u);

    return (3);
}

int autonomous_t26_aqt1_unpack(
    struct autonomous_t26_aqt1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->brk_press = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brk_press |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->res = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->bots = unpack_right_shift_u8(src_p[2], 1u, 0x02u);

    return (0);
}

int autonomous_t26_aqt1_init(struct autonomous_t26_aqt1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_aqt1_t));

    return 0;
}

uint16_t autonomous_t26_aqt1_brk_press_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_t26_aqt1_brk_press_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_t26_aqt1_brk_press_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_aqt1_brk_press_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_aqt1_res_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_aqt1_res_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_aqt1_res_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_aqt1_res_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_aqt1_bots_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_aqt1_bots_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_aqt1_bots_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_aqt1_bots_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int autonomous_t26_aqt2_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt2_t *src_p,
    size_t size)
{
    uint16_t wheel_angle;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    wheel_angle = (uint16_t)src_p->wheel_angle;
    dst_p[0] |= pack_left_shift_u16(wheel_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(wheel_angle, 8u, 0xffu);

    return (2);
}

int autonomous_t26_aqt2_unpack(
    struct autonomous_t26_aqt2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t wheel_angle;

    if (size < 2u) {
        return (-EINVAL);
    }

    wheel_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    wheel_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->wheel_angle = (int16_t)wheel_angle;

    return (0);
}

int autonomous_t26_aqt2_init(struct autonomous_t26_aqt2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_aqt2_t));

    return 0;
}

int16_t autonomous_t26_aqt2_wheel_angle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double autonomous_t26_aqt2_wheel_angle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_t26_aqt2_wheel_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_aqt2_wheel_angle_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int autonomous_t26_aqt3_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt3_t *src_p,
    size_t size)
{
    uint16_t wheel_angle;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    wheel_angle = (uint16_t)src_p->wheel_angle;
    dst_p[0] |= pack_left_shift_u16(wheel_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(wheel_angle, 8u, 0xffu);

    return (2);
}

int autonomous_t26_aqt3_unpack(
    struct autonomous_t26_aqt3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t wheel_angle;

    if (size < 2u) {
        return (-EINVAL);
    }

    wheel_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    wheel_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->wheel_angle = (int16_t)wheel_angle;

    return (0);
}

int autonomous_t26_aqt3_init(struct autonomous_t26_aqt3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_aqt3_t));

    return 0;
}

int16_t autonomous_t26_aqt3_wheel_angle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double autonomous_t26_aqt3_wheel_angle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_t26_aqt3_wheel_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_aqt3_wheel_angle_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int autonomous_t26_aqt4_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt4_t *src_p,
    size_t size)
{
    uint16_t st_angle;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    st_angle = (uint16_t)src_p->st_angle;
    dst_p[0] |= pack_left_shift_u16(st_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(st_angle, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->inertia, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->emer_button, 1u, 0x02u);

    return (3);
}

int autonomous_t26_aqt4_unpack(
    struct autonomous_t26_aqt4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t st_angle;

    if (size < 3u) {
        return (-EINVAL);
    }

    st_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    st_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->st_angle = (int16_t)st_angle;
    dst_p->inertia = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->emer_button = unpack_right_shift_u8(src_p[2], 1u, 0x02u);

    return (0);
}

int autonomous_t26_aqt4_init(struct autonomous_t26_aqt4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_aqt4_t));

    return 0;
}

int16_t autonomous_t26_aqt4_st_angle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double autonomous_t26_aqt4_st_angle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_t26_aqt4_st_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_aqt4_st_angle_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_aqt4_inertia_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_aqt4_inertia_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_aqt4_inertia_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_aqt4_inertia_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_t26_aqt4_emer_button_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_t26_aqt4_emer_button_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_t26_aqt4_emer_button_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool autonomous_t26_aqt4_emer_button_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int autonomous_t26_aqt7_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt7_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->brk_press, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brk_press, 8u, 0xffu);

    return (2);
}

int autonomous_t26_aqt7_unpack(
    struct autonomous_t26_aqt7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->brk_press = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brk_press |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int autonomous_t26_aqt7_init(struct autonomous_t26_aqt7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_t26_aqt7_t));

    return 0;
}

uint16_t autonomous_t26_aqt7_brk_press_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_t26_aqt7_brk_press_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_t26_aqt7_brk_press_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool autonomous_t26_aqt7_brk_press_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
