/**
 * @file autonomous_t26.h
 *
 * @brief This header file was generated by cantools version 41.3.0 Fri Apr 10 18:19:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef AUTONOMOUS_T26_H
#define AUTONOMOUS_T26_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define AUTONOMOUS_T26_ACU_FRAME_ID (0x51u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_FRAME_ID (0x2968u)
#define AUTONOMOUS_T26_DIR_ACT_POSSITION_LOOP_FRAME_ID (0x468u)
#define AUTONOMOUS_T26_AQT1_FRAME_ID (0x710u)
#define AUTONOMOUS_T26_AQT2_FRAME_ID (0x720u)
#define AUTONOMOUS_T26_AQT3_FRAME_ID (0x730u)
#define AUTONOMOUS_T26_AQT4_FRAME_ID (0x740u)
#define AUTONOMOUS_T26_AQT7_FRAME_ID (0x770u)

/* Frame lengths in bytes. */
#define AUTONOMOUS_T26_ACU_LENGTH (8u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_LENGTH (8u)
#define AUTONOMOUS_T26_DIR_ACT_POSSITION_LOOP_LENGTH (8u)
#define AUTONOMOUS_T26_AQT1_LENGTH (3u)
#define AUTONOMOUS_T26_AQT2_LENGTH (2u)
#define AUTONOMOUS_T26_AQT3_LENGTH (2u)
#define AUTONOMOUS_T26_AQT4_LENGTH (3u)
#define AUTONOMOUS_T26_AQT7_LENGTH (2u)

/* Extended or standard frame types. */
#define AUTONOMOUS_T26_ACU_IS_EXTENDED (0)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_IS_EXTENDED (1)
#define AUTONOMOUS_T26_DIR_ACT_POSSITION_LOOP_IS_EXTENDED (1)
#define AUTONOMOUS_T26_AQT1_IS_EXTENDED (0)
#define AUTONOMOUS_T26_AQT2_IS_EXTENDED (0)
#define AUTONOMOUS_T26_AQT3_IS_EXTENDED (0)
#define AUTONOMOUS_T26_AQT4_IS_EXTENDED (0)
#define AUTONOMOUS_T26_AQT7_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define AUTONOMOUS_T26_ACU_IGN_OFF_CHOICE (0u)
#define AUTONOMOUS_T26_ACU_IGN_ON_CHOICE (1u)

#define AUTONOMOUS_T26_ACU_ASMS_OFF_CHOICE (0u)
#define AUTONOMOUS_T26_ACU_ASMS_ON_CHOICE (1u)

#define AUTONOMOUS_T26_ACU_EMERGENCY_OFF_CHOICE (0u)
#define AUTONOMOUS_T26_ACU_EMERGENCY_ON_CHOICE (1u)

#define AUTONOMOUS_T26_ACU_AS_STATE_OFF_CHOICE (1u)
#define AUTONOMOUS_T26_ACU_AS_STATE_READY_CHOICE (2u)
#define AUTONOMOUS_T26_ACU_AS_STATE_DRIVING_CHOICE (3u)
#define AUTONOMOUS_T26_ACU_AS_STATE_EMERGENCY_CHOICE (4u)
#define AUTONOMOUS_T26_ACU_AS_STATE_FINISH_CHOICE (5u)

#define AUTONOMOUS_T26_ACU_ACU_STATE_INIT_CHOICE (0u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_MISSION_SELECT_CHOICE (1u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_JETSON_WAITING_CHOICE (2u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_INIT_SEQUENCE_CHOICE (3u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_READY_CHOICE (4u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_DRIVING_CHOICE (5u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_EBS_ERROR_CHOICE (6u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_EMERGENCY_CHOICE (7u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_FINISHED_CHOICE (8u)
#define AUTONOMOUS_T26_ACU_ACU_STATE_MANUAL_CHOICE (9u)

#define AUTONOMOUS_T26_ACU_ASSI_STATE_OFF_CHOICE (1u)
#define AUTONOMOUS_T26_ACU_ASSI_STATE_READY_CHOICE (2u)
#define AUTONOMOUS_T26_ACU_ASSI_STATE_DRIVING_CHOICE (3u)
#define AUTONOMOUS_T26_ACU_ASSI_STATE_EMERGENCY_CHOICE (4u)
#define AUTONOMOUS_T26_ACU_ASSI_STATE_FINISH_CHOICE (5u)

#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_NO__FAULT_CHOICE (0u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_MOTOR__OVER_TEMPERATURE_CHOICE (1u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_OVER_CURRENT_CHOICE (2u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_OVER_VOLTAGE_CHOICE (3u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_ENCODE__FAULT_CHOICE (4u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_MOSFET__OVER_TEMPERATURE_CHOICE (5u)
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_MOTOR__LOCK_UP_CHOICE (6u)

/* Frame Names. */
#define AUTONOMOUS_T26_ACU_NAME "ACU"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_NAME "dir_actuator_feedback"
#define AUTONOMOUS_T26_DIR_ACT_POSSITION_LOOP_NAME "dir_act_possition_loop"
#define AUTONOMOUS_T26_AQT1_NAME "AQT1"
#define AUTONOMOUS_T26_AQT2_NAME "AQT2"
#define AUTONOMOUS_T26_AQT3_NAME "AQT3"
#define AUTONOMOUS_T26_AQT4_NAME "AQT4"
#define AUTONOMOUS_T26_AQT7_NAME "AQT7"

/* Signal Names. */
#define AUTONOMOUS_T26_ACU_IGN_NAME "IGN"
#define AUTONOMOUS_T26_ACU_ASMS_NAME "ASMS"
#define AUTONOMOUS_T26_ACU_EMERGENCY_NAME "EMERGENCY"
#define AUTONOMOUS_T26_ACU_AS_STATE_NAME "AS_STATE"
#define AUTONOMOUS_T26_ACU_MISSION_SELECT_NAME "Mission_select"
#define AUTONOMOUS_T26_ACU_ACU_STATE_NAME "ACU_STATE"
#define AUTONOMOUS_T26_ACU_ASSI_STATE_NAME "ASSI_STATE"
#define AUTONOMOUS_T26_ACU_ACU_CPU_TEMP_NAME "ACU_CPU_TEMP"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_POSITION_NAME "Position"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_SPEED_NAME "Speed"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_CURRENT_NAME "Current"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_TEMPERATURE_NAME "Temperature"
#define AUTONOMOUS_T26_DIR_ACTUATOR_FEEDBACK_ERROR_CODES_NAME "Error_codes"
#define AUTONOMOUS_T26_DIR_ACT_POSSITION_LOOP_POSITION_NAME "POSITION"
#define AUTONOMOUS_T26_AQT1_BRK_PRESS_NAME "BRK_PRESS"
#define AUTONOMOUS_T26_AQT1_RES_NAME "RES"
#define AUTONOMOUS_T26_AQT1_BOTS_NAME "BOTS"
#define AUTONOMOUS_T26_AQT2_WHEEL_ANGLE_NAME "WHEEL_ANGLE"
#define AUTONOMOUS_T26_AQT3_WHEEL_ANGLE_NAME "WHEEL_ANGLE"
#define AUTONOMOUS_T26_AQT4_ST_ANGLE_NAME "ST_ANGLE"
#define AUTONOMOUS_T26_AQT4_INERTIA_NAME "INERTIA"
#define AUTONOMOUS_T26_AQT4_EMER_BUTTON_NAME "EMER_BUTTON"
#define AUTONOMOUS_T26_AQT7_BRK_PRESS_NAME "BRK_PRESS"

/**
 * Signals in message ACU.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_acu_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ign;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t asms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t emergency;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t as_state;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t mission_select;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t acu_state;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t assi_state;

    /**
     * Range: 0..255 (0..255 º)
     * Scale: 1
     * Offset: 0
     */
    uint8_t acu_cpu_temp;
};

/**
 * Signals in message dir_actuator_feedback.
 *
 * 
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_dir_actuator_feedback_t {
    /**
     * Range: -3200..3200 (-32000..32000 º)
     * Scale: 10
     * Offset: 0
     */
    uint16_t position;

    /**
     * Range: -152..152 (-32000..32000 RPM)
     * Scale: 210
     * Offset: 0
     */
    uint16_t speed;

    /**
     * The current is of int16 type, with values -6000 to 6000 representing -60 to 60 A
     *
     * Range: -
     * Scale: 100
     * Offset: 0
     */
    uint16_t current;

    /**
     * Range: -20..127 (-20..127 º)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temperature;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t error_codes;
};

/**
 * Signals in message dir_act_possition_loop.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_dir_act_possition_loop_t {
    /**
     * Range: -
     * Scale: 1000
     * Offset: 0
     */
    int32_t position;
};

/**
 * Signals in message AQT1.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_aqt1_t {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t brk_press;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t res;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bots;
};

/**
 * Signals in message AQT2.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_aqt2_t {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    int16_t wheel_angle;
};

/**
 * Signals in message AQT3.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_aqt3_t {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    int16_t wheel_angle;
};

/**
 * Signals in message AQT4.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_aqt4_t {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    int16_t st_angle;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t inertia;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t emer_button;
};

/**
 * Signals in message AQT7.
 *
 * All signal values are as on the CAN bus.
 */
struct autonomous_t26_aqt7_t {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t brk_press;
};

/**
 * Pack message ACU.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_acu_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_acu_t *src_p,
    size_t size);

/**
 * Unpack message ACU.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_acu_unpack(
    struct autonomous_t26_acu_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ACU.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_acu_init(struct autonomous_t26_acu_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_ign_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_ign_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_ign_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_ign_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_asms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_asms_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_asms_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_asms_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_emergency_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_emergency_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_emergency_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_emergency_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_as_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_as_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_as_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_as_state_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_mission_select_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_mission_select_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_mission_select_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_mission_select_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_acu_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_acu_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_acu_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_acu_state_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_assi_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_assi_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_assi_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_assi_state_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_acu_acu_cpu_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_acu_acu_cpu_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_acu_cpu_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_acu_acu_cpu_temp_is_in_phys_range(double value);

/**
 * Pack message dir_actuator_feedback.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_dir_actuator_feedback_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_dir_actuator_feedback_t *src_p,
    size_t size);

/**
 * Unpack message dir_actuator_feedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_dir_actuator_feedback_unpack(
    struct autonomous_t26_dir_actuator_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from dir_actuator_feedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_dir_actuator_feedback_init(struct autonomous_t26_dir_actuator_feedback_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t autonomous_t26_dir_actuator_feedback_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_actuator_feedback_position_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_position_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_position_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t autonomous_t26_dir_actuator_feedback_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_actuator_feedback_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_speed_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t autonomous_t26_dir_actuator_feedback_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_actuator_feedback_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_dir_actuator_feedback_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_actuator_feedback_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_temperature_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_dir_actuator_feedback_error_codes_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_actuator_feedback_error_codes_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_error_codes_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_actuator_feedback_error_codes_is_in_phys_range(double value);

/**
 * Pack message dir_act_possition_loop.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_dir_act_possition_loop_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_dir_act_possition_loop_t *src_p,
    size_t size);

/**
 * Unpack message dir_act_possition_loop.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_dir_act_possition_loop_unpack(
    struct autonomous_t26_dir_act_possition_loop_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from dir_act_possition_loop.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_dir_act_possition_loop_init(struct autonomous_t26_dir_act_possition_loop_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t autonomous_t26_dir_act_possition_loop_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_dir_act_possition_loop_position_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_act_possition_loop_position_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_dir_act_possition_loop_position_is_in_phys_range(double value);

/**
 * Pack message AQT1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_aqt1_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt1_t *src_p,
    size_t size);

/**
 * Unpack message AQT1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_aqt1_unpack(
    struct autonomous_t26_aqt1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AQT1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_aqt1_init(struct autonomous_t26_aqt1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t autonomous_t26_aqt1_brk_press_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt1_brk_press_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_brk_press_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_brk_press_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_aqt1_res_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt1_res_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_res_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_res_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_aqt1_bots_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt1_bots_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_bots_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt1_bots_is_in_phys_range(double value);

/**
 * Pack message AQT2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_aqt2_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt2_t *src_p,
    size_t size);

/**
 * Unpack message AQT2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_aqt2_unpack(
    struct autonomous_t26_aqt2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AQT2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_aqt2_init(struct autonomous_t26_aqt2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t autonomous_t26_aqt2_wheel_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt2_wheel_angle_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt2_wheel_angle_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt2_wheel_angle_is_in_phys_range(double value);

/**
 * Pack message AQT3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_aqt3_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt3_t *src_p,
    size_t size);

/**
 * Unpack message AQT3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_aqt3_unpack(
    struct autonomous_t26_aqt3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AQT3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_aqt3_init(struct autonomous_t26_aqt3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t autonomous_t26_aqt3_wheel_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt3_wheel_angle_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt3_wheel_angle_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt3_wheel_angle_is_in_phys_range(double value);

/**
 * Pack message AQT4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_aqt4_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt4_t *src_p,
    size_t size);

/**
 * Unpack message AQT4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_aqt4_unpack(
    struct autonomous_t26_aqt4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AQT4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_aqt4_init(struct autonomous_t26_aqt4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t autonomous_t26_aqt4_st_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt4_st_angle_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_st_angle_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_st_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_aqt4_inertia_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt4_inertia_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_inertia_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_inertia_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t autonomous_t26_aqt4_emer_button_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt4_emer_button_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_emer_button_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt4_emer_button_is_in_phys_range(double value);

/**
 * Pack message AQT7.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int autonomous_t26_aqt7_pack(
    uint8_t *dst_p,
    const struct autonomous_t26_aqt7_t *src_p,
    size_t size);

/**
 * Unpack message AQT7.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int autonomous_t26_aqt7_unpack(
    struct autonomous_t26_aqt7_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AQT7.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int autonomous_t26_aqt7_init(struct autonomous_t26_aqt7_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t autonomous_t26_aqt7_brk_press_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double autonomous_t26_aqt7_brk_press_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt7_brk_press_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool autonomous_t26_aqt7_brk_press_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
